// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang.Models;

#nullable disable

namespace WebBanHang.Migrations
{
    [DbContext(typeof(ShopHueDaQuaContext))]
    partial class ShopHueDaQuaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogDanhMuc", b =>
                {
                    b.Property<int>("IddanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("IDDanhMuc");

                    b.Property<int>("Idblog")
                        .HasColumnType("int")
                        .HasColumnName("IDBlog");

                    b.HasKey("IddanhMuc", "Idblog")
                        .HasName("PK__Blog_Dan__2CA3B369A2A301E1");

                    b.HasIndex("Idblog");

                    b.ToTable("Blog_DanhMuc", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.Blog", b =>
                {
                    b.Property<int>("Idblog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDBlog");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idblog"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("NgayDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Idblog")
                        .HasName("PK__Blog__3CFB8BBEFD47FDE5");

                    b.ToTable("Blog", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("IdchiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDChiTietDonHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdchiTietDonHang"));

                    b.Property<int?>("IddonHang")
                        .HasColumnType("int")
                        .HasColumnName("IDDonHang");

                    b.Property<string>("IdsanPham")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("IDSanPham");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("soLuong");

                    b.HasKey("IdchiTietDonHang")
                        .HasName("PK__ChiTietD__EB5BBDC08FB319F0");

                    b.HasIndex("IddonHang");

                    b.HasIndex("IdsanPham");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("IdchiTietGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDChiTietGioHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdchiTietGioHang"));

                    b.Property<int?>("IdgioHang")
                        .HasColumnType("int")
                        .HasColumnName("IDGioHang");

                    b.Property<string>("IdsanPham")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("IDSanPham");

                    b.Property<int?>("SoLuongDat")
                        .HasColumnType("int");

                    b.HasKey("IdchiTietGioHang")
                        .HasName("PK__ChiTietG__5AC4B7C596B05E61");

                    b.HasIndex("IdgioHang");

                    b.HasIndex("IdsanPham");

                    b.ToTable("ChiTietGioHang", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.DanhGia", b =>
                {
                    b.Property<int>("IddanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDanhGia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddanhGia"));

                    b.Property<int?>("IdchiTietDonHang")
                        .HasColumnType("int")
                        .HasColumnName("IDChiTietDonHang");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDung");

                    b.Property<int?>("SoSao")
                        .HasColumnType("int")
                        .HasColumnName("soSao");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGian")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IddanhGia")
                        .HasName("PK__DanhGia__C216E48D3CB36D6E");

                    b.HasIndex("IdchiTietDonHang");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("WebBanHang.Models.DanhMuc", b =>
                {
                    b.Property<int>("IddanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDanhMuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddanhMuc"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<string>("SanPhamIdsanPham")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenDanhMuc");

                    b.HasKey("IddanhMuc")
                        .HasName("PK__DanhMuc__DF6C0BD24988B091");

                    b.HasIndex("SanPhamIdsanPham");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.DonHang", b =>
                {
                    b.Property<int>("IddonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDonHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddonHang"));

                    b.Property<int?>("IdkhachHang")
                        .HasColumnType("int")
                        .HasColumnName("IDKhachHang");

                    b.Property<int?>("IdthanhToan")
                        .HasColumnType("int")
                        .HasColumnName("IDThanhToan");

                    b.Property<DateOnly?>("NgayLap")
                        .HasColumnType("date")
                        .HasColumnName("ngayLap");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("tongTien");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IddonHang")
                        .HasName("PK__DonHang__9CA232F791CCA0F3");

                    b.HasIndex("IdkhachHang");

                    b.HasIndex("IdthanhToan");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.GioHang", b =>
                {
                    b.Property<int>("IdgioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDGioHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdgioHang"));

                    b.Property<int?>("IdkhachHang")
                        .HasColumnType("int")
                        .HasColumnName("IDKhachHang");

                    b.HasKey("IdgioHang")
                        .HasName("PK__GioHang__0B2CDDAE81E1B2E2");

                    b.HasIndex("IdkhachHang");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.HinhAnhSanPham", b =>
                {
                    b.Property<int>("IdhinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDHinhAnh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdhinhAnh"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("IdsanPham")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("IDSanPham");

                    b.HasKey("IdhinhAnh")
                        .HasName("PK__HinhAnhS__2B573EE86387A017");

                    b.HasIndex("IdsanPham");

                    b.ToTable("HinhAnhSanPham", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.KhachHang", b =>
                {
                    b.Property<int>("IdkhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDKhachHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdkhachHang"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hoTen");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("matKhau");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("soDienThoai")
                        .IsFixedLength();

                    b.Property<string>("TaiKhoan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("taiKhoan");

                    b.HasKey("IdkhachHang")
                        .HasName("PK__KhachHan__5A7167B563B525D7");

                    b.HasIndex(new[] { "Email" }, "UQ_KhachHang_Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex(new[] { "TaiKhoan" }, "UQ_KhachHang_TaiKhoan")
                        .IsUnique()
                        .HasFilter("[taiKhoan] IS NOT NULL");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.SanPham", b =>
                {
                    b.Property<string>("IdsanPham")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("IDSanPham");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("IddanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("IDDanhMuc");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("XuatXu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdsanPham")
                        .HasName("PK__SanPham__9D45E58AC7ECC711");

                    b.HasIndex("IddanhMuc");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.ThanhToan", b =>
                {
                    b.Property<int>("IdthanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDThanhToan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdthanhToan"));

                    b.Property<string>("MaThanhToan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenThanhToan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdthanhToan")
                        .HasName("PK__ThanhToa__DC57C3A13F17D195");

                    b.HasIndex(new[] { "MaThanhToan" }, "UQ_ThanhToan_MaThanhToan")
                        .IsUnique()
                        .HasFilter("[MaThanhToan] IS NOT NULL");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("BlogDanhMuc", b =>
                {
                    b.HasOne("WebBanHang.Models.Blog", null)
                        .WithMany()
                        .HasForeignKey("Idblog")
                        .IsRequired()
                        .HasConstraintName("FK__Blog_Danh__IDBlo__46E78A0C");

                    b.HasOne("WebBanHang.Models.DanhMuc", null)
                        .WithMany()
                        .HasForeignKey("IddanhMuc")
                        .IsRequired()
                        .HasConstraintName("FK__Blog_Danh__IDDan__45F365D3");
                });

            modelBuilder.Entity("WebBanHang.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("WebBanHang.Models.DonHang", "IddonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IddonHang")
                        .HasConstraintName("FK__ChiTietDo__IDDon__52593CB8");

                    b.HasOne("WebBanHang.Models.SanPham", "IdsanPhamNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IdsanPham")
                        .HasConstraintName("FK__ChiTietDo__IDSan__534D60F1");

                    b.Navigation("IddonHangNavigation");

                    b.Navigation("IdsanPhamNavigation");
                });

            modelBuilder.Entity("WebBanHang.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("WebBanHang.Models.GioHang", "IdgioHangNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("IdgioHang")
                        .HasConstraintName("FK__ChiTietGi__IDGio__403A8C7D");

                    b.HasOne("WebBanHang.Models.SanPham", "IdsanPhamNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("IdsanPham")
                        .HasConstraintName("FK__ChiTietGi__IDSan__412EB0B6");

                    b.Navigation("IdgioHangNavigation");

                    b.Navigation("IdsanPhamNavigation");
                });

            modelBuilder.Entity("WebBanHang.Models.DanhGia", b =>
                {
                    b.HasOne("WebBanHang.Models.ChiTietDonHang", "IdchiTietDonHangNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("IdchiTietDonHang")
                        .HasConstraintName("FK__DanhGia__IDChiTi__5629CD9C");

                    b.Navigation("IdchiTietDonHangNavigation");
                });

            modelBuilder.Entity("WebBanHang.Models.DanhMuc", b =>
                {
                    b.HasOne("WebBanHang.Models.SanPham", null)
                        .WithMany("DanhMucs")
                        .HasForeignKey("SanPhamIdsanPham");
                });

            modelBuilder.Entity("WebBanHang.Models.DonHang", b =>
                {
                    b.HasOne("WebBanHang.Models.KhachHang", "IdkhachHangNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdkhachHang")
                        .HasConstraintName("FK__DonHang__IDKhach__4E88ABD4");

                    b.HasOne("WebBanHang.Models.ThanhToan", "IdthanhToanNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdthanhToan")
                        .HasConstraintName("FK__DonHang__IDThanh__4F7CD00D");

                    b.Navigation("IdkhachHangNavigation");

                    b.Navigation("IdthanhToanNavigation");
                });

            modelBuilder.Entity("WebBanHang.Models.GioHang", b =>
                {
                    b.HasOne("WebBanHang.Models.KhachHang", "IdkhachHangNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("IdkhachHang")
                        .HasConstraintName("FK__GioHang__IDKhach__398D8EEE");

                    b.Navigation("IdkhachHangNavigation");
                });

            modelBuilder.Entity("WebBanHang.Models.HinhAnhSanPham", b =>
                {
                    b.HasOne("WebBanHang.Models.SanPham", "IdsanPhamNavigation")
                        .WithMany("HinhAnhSanPhams")
                        .HasForeignKey("IdsanPham")
                        .HasConstraintName("FK__HinhAnhSa__IDSan__49C3F6B7");

                    b.Navigation("IdsanPhamNavigation");
                });

            modelBuilder.Entity("WebBanHang.Models.SanPham", b =>
                {
                    b.HasOne("WebBanHang.Models.DanhMuc", "IddanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IddanhMuc")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IddanhMucNavigation");
                });

            modelBuilder.Entity("WebBanHang.Models.ChiTietDonHang", b =>
                {
                    b.Navigation("DanhGia");
                });

            modelBuilder.Entity("WebBanHang.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebBanHang.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("WebBanHang.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("WebBanHang.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("WebBanHang.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("DanhMucs");

                    b.Navigation("HinhAnhSanPhams");
                });

            modelBuilder.Entity("WebBanHang.Models.ThanhToan", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
